### ISSUE TITLE
json encoder should handle NaN and Infinity

### ISSUE THREAD

**Issue by chriddyp** [plotly/python-api#202]
python's json encoder does this really annoying thing where it uses "extended" JSON, which includes NaN and Infinity. This means that `JSON.parse()` (javascript) of `NaN` fails! We should probably just replace with `None`

reference: http://stackoverflow.com/questions/17503981/is-there-a-way-to-override-pythons-json-handler

cc @theengineear

**Comment by theengineear** [comment]
Yup, good call.

**Comment by theengineear** [comment]
This is *fairly* simple to implement based on the link you provided.

One caveat. What about this case:

(1) user has `Inf` and `NaN` from some calculations
(2) user uploads that data to plotly
(3) collaborator snags data from plotly
(4) collaborator *decodes* and get's `None` now!

If they're using numpy, they can get back 'NaN' pretty easily:

http://stackoverflow.com/questions/19456239/convert-python-list-with-none-values-to-numpy-array-with-nan-values

But since it's a many-to-one mapping, there's obviously no way to get both `NaN` and `Inf` back.

I think I'm okay with this if we document the link I provided above.
