### ISSUE TITLE
iPlot return object url parameter empty

### ISSUE THREAD

**Issue by anmolgarg** [plotly/python-api#211]
the return from a py.iplot_mpl url paramater is None

**Comment by etpinard** [comment]
Yikes!

Can you help us out a little bit? Do you have a code snippet that you could send us?

**Comment by anmolgarg** [comment]
> import matplotlib.pyplot as plt
import plotly.plotly as py
import random

> foo = [random.random() for j in range(100)]
fig = plt.figure(figsize=(16, 9)); 
plt.plot(foo)
output = py.iplot_mpl(fig)
print output.url

**Comment by theengineear** [comment]
@anmolgarg , so the plotly display object inherits the `url` param from the IPython HTML display object. Which is why it exists but is empty.

However, we stowe the url information in `resource`.

You should be able to do something like:

```
import plotly.plotly as py
from plotly.graph_objs import Scatter
obj = py.iplot([Scatter(y=[1,2,3])], filename='messin')
print obj.resource
```

And then, dropping `obj` into an output cell should still display the iframe for you.

Let me know if that works for you (including that the domain name displays correctly)

**Comment by anmolgarg** [comment]
@theengineear, thanks, using obj.resource works for me in the fashion I expected.
